server:
  port: 8080
  servlet:
    context-path: /Crud
spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/codelai"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true